public with sharing class EventDetails_Controller {
  //@AuraEnabled
  //public static Campaign getEventDetails(String eventId) {
  //  List<Campaign> campaignList = [SELECT ID,
  //  Name,
  //  StartDate,
  //  EndDate,
  //  Description_Rich__c,
  //  Location__c,
  //  Location_Address__c,
  //  Featured_Image__c,
  //  Start_Time__c,
  //  End_Time__c,
  //  Primary_Contact__c,
  //  Primary_Contact__r.Phone,
  //  Primary_Contact__r.Email,
  //  Primary_Contact__r.FirstName,
  //  Primary_Contact__r.LastName FROM Campaign WHERE id = :eventId];
  //  return campaignList.isEmpty() ? null : campaignList[0];
  //}
}