public class PostsController {
  //@AuraEnabled
  //public static List<Post__c> getLatestBlogPosts() {
  //  return [SELECT Id,Author__c,Type__c,Title__c,Featured_Image__c,Date_Published__c,Content_Rich__c,Content__c FROM Post__c WHERE Type__c = 'Blog' ORDER BY Date_Published__c DESC LIMIT 3];
  //}

  //@AuraEnabled
  //public static List<Post__c> getAllBlogPosts() {
  //  return [SELECT Id,Author__c,Type__c,Title__c,Featured_Image__c,Date_Published__c,Content_Rich__c,Content__c FROM Post__c WHERE Type__c = 'Blog' ORDER BY Date_Published__c DESC];
  //}

  //@AuraEnabled
  //public static List<Post__c> getAllNewsPosts() {
  //  return [SELECT Id,Author__c,Type__c,Title__c,Featured_Image__c,Date_Published__c,Content_Rich__c,Content__c FROM Post__c WHERE Type__c = 'News' ORDER BY Date_Published__c DESC];
  //}
}