@isTest
private class RaffleActiveController_Test {
  //static testMethod void RaffleActiveController() {

  //  Campaign c1 = new Campaign();

  //  c1.Name = 'test';
  //  c1.StartDate = Date.today();
  //  c1.EndDate = Date.today();
  //  c1.Description_Rich__c = 'test';
  //  c1.Raffle_Ticket_Price__c = 'test';
  //  c1.Featured_Image__c = 'test';
  //  insert c1;

  //  Test.StartTest();
  //  List<Campaign> returnData = RaffleActive_Controller.getRaffleList();
  //  system.assertNotEquals(returnData.size(), 1);
  //  Test.StopTest();

  //}
}